version: '3'
services:
  app:
    build: .
    container_name: "docker-for-rails"
    ports:
      - "3000:3000"
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/home/docker-for-rails
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
